### ISSUE TITLE
Missing File!!!

### ISSUE THREAD

**Issue by BlueLoneWolf** [arduino-libraries/LiquidCrystal#17]
Code won't compile as this Library is missing a ".h" file, called "seesaw.h"!!!, would be nice if someone could point where this file is located if in any other library, thanks

**Comment by per1234** [comment]
There's no reference to a file named seesaw.h anywhere in this library so it's not appropriate to report this issue here.

If you need help you should instead post on the Arduino Forum. I'm sure we'll be able to help you with your problem over there. Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
